apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "eventrouter.fullname" . }}
  namespace: {{ .Values.monitoringNamespace }}
  labels:
    {{- include "eventrouter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "eventrouter.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace | quote }}
  endpoints:
  - port: http-metrics
    interval: 15s
