replicaCount: 1

image:
  repository: doc.propelmedia.com/platform/eventrouter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0.3.0.pes1.0

imagePullSecrets:
  - name: platform-registry
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true


service:
  type: ClusterIP
  port: 8080
  
podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
#   readOnlyRootFilesystem: true
   runAsNonRoot: true
   runAsUser: 1000

resources:
  limits:
     cpu: 200m
     memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector:
  platform-node: "true"
tolerations:
  - effect: NoSchedule
    key: platform-node
    
affinity: {}


monitoringNamespace: platform