pipeline:
  image: platform/golang:1.23.2.pes1
  stages:
    "Build Binary":
      cache:
        - path: /gopath
      env:
        GOPATH: /gopath
        CGO_ENABLED: 0
        GOOS: linux
      steps:
        - |
          go mod download
          go build .

    "Build Docker Image":
      imageBuild: &imageBuild
        push: false
        name: platform/eventrouter
        tags:
          - 1.0.1
        securityScan:
          failSeverity: CRITICAL
    
    "Deploy Docker Image":
      branch: master
      imageBuild:
        <<: *imageBuild
        push: true
