pipeline:
  image: platform/go:1.15
  stages:
    "Build Binary":
      cache:
        - path: /gopath
      env:
        GOPATH: /gopath
        CGO_ENABLED: 0
        GOOS: linux
      steps:
        - |
          go mod download
          go build

    "Build Docker Image":
      imageBuild: &imageBuild
        push: false
        name: platform/eventrouter
        tags:
          - 0.3.0.pes1.1
    
    "Deploy Docker Image":
      branch: master
      imageBuild:
        <<: *imageBuild
        push: true